### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by ns1000** [projectpai/paicoin#185]
Standard mining using a custom mining key does not work because mining addresses have been hardcoded in to the node code. So how does mining work?

**Comment by projectpaiadmin** [comment]
@ns1000 Thank you for your inquiry, and we apologize for the delayed response.

PAI Coin currently implements a coinbase address whitelist at the protocol level. This means that, when a miner submits a new block, in addition to the standard block validations performed in CheckBlock(), the specified coinbase payout address must match one of those on the mining address whitelist.

This whitelist solution has been implemented as a preventative mechanism against potentially catastrophic vulnerabilities, like a 51% attack. In an effort to remove the coinbase address whitelist without compromising the security of the PAI Blockchain, some Project PAI contributors have proposed a new Hybrid PoW/PoS protocol, which is currently under development.

You can read the proposal here: https://projectpai.com/assets/files/whitepaper/Prospective-Hybrid-Consensus-for-Project-PAI.pdf

Ongoing development work has begun here: https://github.com/projectpai/paicoin/tree/feature/sha3
