### ISSUE TITLE
Add additional testnet miners

### ISSUE THREAD

**Issue by mharvilla** [projectpai/paicoin#284]
Add 2-3 additional testnet mining instances in AWS to increase the block find rate, which is currently quite slow. 
When complete, please comment the instances created and their IPs on this ticket.

**Comment by jaschadub** [comment]
172.31.43.167 paicoin-testnet-miner04
172.31.34.226 paicoin-testnet-miner05

**Comment by jaschadub** [comment]
We could just turn this into a scaling group and then can schedule or leverage spot instances to save.

**Comment by mharvilla** [comment]
@jaschadub Good idea, let's do it.
