### ISSUE TITLE
About Pai source code and BTC source code

### ISSUE THREAD

**Issue by ZexiFangkong** [projectpai/paicoin#29]
hello
A quick look at your source code shows that the overall file architecture is pretty much the same as bitcoin, and the implementation of the source code is pretty much the same in many places.
Excuse me, do you have any connection with BitCoin? Or do you do the underlying architecture by referring to its essence?

**Comment by ZexiFangkong** [comment]
Isn't there anyone in the community?

**Comment by projectpaiadmin** [comment]
Hi, @ZexiFangkong thank you so much for your inquiry! Project PAI really appreciates your interest. As a decentralized, open-source venture, Project PAI envisions community involvement in, and consensus on, the evolutionary direction of the project. The Project PAI white papers, which you can find at https://projectpai.com/pai-whitepaper set the stage for the original vision of PAI Coin and Personal AI, but as with all open-source activities, the ultimate trajectory of the project, from broad strokes to gritty technical detail, should be decided by the community. Project PAI has been careful to implement the components outlined in the technical white paper with minimal changes to PAI Coin with respect to Bitcoin outside of these topics, choosing instead to leave such decisions to our passionate and capable technical community. The Project PAI development roadmap follows:

Q1 2018 (January - March) | PAI Coin Mainnet launched ✓
Q2 2018 (April - June) | PAI Up mobile wallet (iOS/Android) launched ✓
ObEN PAIYO (iOS/Android) launched ✓
PAI Coin distributed to pre-sale investors ✓
Q3 2018 (July - September) | WeChat walletPAI Up Desktop wallets (Windows/macOS)
Smart contract and token support
Q4 2018 (October - December) | Test Proof of Useful Work (PoUW) protocol with early adopters
Q1 2019 (January - March) | Dedicated chip development for PAI
