### ISSUE TITLE
Unspent check fails despite plenty of PAI

### ISSUE THREAD

**Issue by pgerzani** [projectpai/paicoin#317]
On the auto staker node, I was trying to send Mark some coin to test with.  However, it said that there was insufficient funds:
```
paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 5000
error code: -4
error message:
Insufficient funds
```
However, the account balances show that there should not be a problem:
```
 paicoin-cli listaccounts
{
  "": 1213999.86223656
}
```
So, out of curiosity, I then checked the unspent vouts list:
```
paicoin-cli listunspent
```
and it was a huge list many of which were non-zero.  However, there were a lot that were zero:
```
  {
    "txid": "ad46a2aab41c8b91dd2a654f2c5bb27d9dff34826cc313abe991ea29dca2feff",
    "vout": 3,
    "address": "MnWWoz1QWqcAA3FjjHZUTzUujQfPVAjo9e",
    "scriptPubKey": "76a914a784843aaafb3136c0cff03bec06db1663c08acf88ac",
    "amount": 0.00000000,
    "confirmations": 547,
    "spendable": true,
    "solvable": true,
    "safe": true
  }
```
which makes me think this is the cause of the failure when trying to send funds?  I would expect the unspent list would not include vouts with an amount of 0, unless that is necessary for some other reason?

**Comment by sebastianrusu** [comment]
@pgerzani The zero amount outputs seem to be the contribution change outputs for ticket purchases. Since the funding transaction for the ticket purchase is customized to have outputs exactly as needed by the ticket purchase, these changes are usually zero. However, the protocol itself does not prevent having them non-zero. So, I guess the correct approach would be to just discard all zero outputs from the UTXO list.

**Comment by pgerzani** [comment]
@sebastianrusu Unfortunately, the issue remains after deploying your change.  I did some additional testing as you can see here and the smaller amounts do work, but given it is an `Insufficient funds` error and not a transaction size issue, I don't think it is due to a big list of vins.

```
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 10000
error code: -4
error message:
Insufficient funds
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 5000
error code: -4
error message:
Insufficient funds
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 5
6e1e8ab15426878b15123ab18b8901690f1461d26ff9208169eeb6844a5552fb
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 100
24a995e9cb9a6c13037ab050ef97b56d9b6b7fefa41ab740c0f21e8800dcbd9d
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 1000
c78a977f7ec1f3ed4989925ba299ab426b644ef5ff6535998b0cbd0b47f28e4c
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 3000
error code: -4
error message:
Insufficient funds
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 2000
error code: -4
error message:
Insufficient funds
ubuntu@AutoStake:~$ paicoin-cli sendfrom "" MZkMYK2YnKNqMV7m77CMj7KtraL52RbgWx 1500
error code: -4
error message:
Insufficient funds
ubuntu@AutoStake:~$ paicoin-cli listaccounts
{
  "": 1788894.96354076
}
```

I've also attached the full output of the unspents list.  I see plenty that should make up the 5k or 10k requests without issue, however I just noticed that they have `spendable` as `false` so perhaps that is the issue?
[unspents.txt](https://github.com/projectpai/paicoin/files/5184184/unspents.txt)

**Comment by sebastianrusu** [comment]
@pgerzani The outputs in the attached file seem to be vote or revocation outputs and according to the consensus rules these are considered matured after the same number of blocks like the coinbase transactions, in our case 100, that is why they show as unspendable. If needed, we can change this policy, but I think this is a good protection, although maybe too strict.
