### ISSUE TITLE
The RPC command starticketbuyer does not work with the provided examples

### ISSUE THREAD

**Issue by pgerzani** [projectpai/paicoin#322]
As part of my investigation into why ticket buying was not working, I was trying to use the `startticketbuyer` call.  However, I kept getting RPC errors even using the examples from the help text:
```
 paicoin-cli startticketbuyer "" 500000 "" "" "" "" 0 1
```
I kept receiving JSON parse errors.  Can you please double-check this call to ensure that it works as intended.

**Comment by sebastianrusu** [comment]
This issue is solved in https://github.com/projectpai/paicoin/pull/361.
