### ISSUE TITLE
Update auto voter behavior to vote on all tips at the current height, not just active

### ISSUE THREAD

**Issue by pgerzani** [projectpai/paicoin#351]
Currently, the auto voter seems to only vote on the active tip for the current height.  As a result, in the event of a chain rollback, votes aren't submitted for the forks to allow that chain to move forward.

Please update the auto voter so that it submits any votes it may have for any active tips of the current height that it is aware of.

**Comment by sebastianrusu** [comment]
This has been implemented in https://github.com/projectpai/paicoin/pull/358.
