### ISSUE TITLE
Consider including install_db4.sh script in contrib

### ISSUE THREAD

**Issue by mharvilla** [projectpai/paicoin#359]
Following [this guide](https://medium.com/coincorner/bitcoin-core-development-on-macos-a-step-by-step-guide-5ecf8b17eb49) for compiling Bitcoin Core on macOS, it calls for the `contrib/install_db4.sh` script, which I copied from the `bitcoin` repository. Perhaps we should include it in the paicoin repository, as well?

**Comment by pgerzani** [comment]
Included and updated docs to reference it.
