### ISSUE TITLE
User reports issue with wallet

### ISSUE THREAD

**Issue by mharvilla** [projectpai/paicoin#383]
There are ongoing issues with the attached wallet (also see chat with sebastian for more information).

I’ve built the chain from scratch using this wallet a couple times and it gives different results for `getbalance`; the this last rebuild when I tried doing a `rescanblockchain` it threw  `CDB: Error -30974, can't open database wallet.dat`.

I’m wondering what's wrong and if there’s at least a way to export private keys such that they can be imported into another wallet to recover funds/tickets.

**wallet-xiao-xing-xing.dat file shared directly**

**Comment by sebastianrusu** [comment]
To export the wallet, including the private keys, you can use the **dumpwallet** RPC call:
   `paicoin-cli dumpwallet filename`

**IMPORTANT!** Please note that this command exports the wallet in plain text, so extra care must be taken with that file. Do NOT send that file over network, especially via e-mail or other unencrypted channel and do NOT store that file in an insecure place.

To import a wallet from a file, use the **importwallet** RPC call:
   `paicoin-cli importwallet filename`
